Promote dev dependencies action
homagames/unity-ci-environment pull request #20
Opened 2023-08-02 15:09 UTC by homapf

2023-08-02 15:43 UTC, manelizzard requested changes
Asking to generalize `homa_dependencies....` variables

2023-08-02 15:43 UTC, manelizzard commented on .github/actions/promote-dev-dependencies/promote-dev-dependencies.sh
> +    local homa_dependencies_key="$2"
Can we generalize this variable name?

2023-08-02 15:43 UTC, manelizzard commented on .github/actions/promote-dev-dependencies/promote-dev-dependencies.sh
> +    local homa_dependencies_key="$2"
Same here

2023-08-02 15:48 UTC, homapf commented on .github/actions/promote-dev-dependencies/promote-dev-dependencies.sh
> +    local homa_dependencies_key="$2"
Done

2023-08-02 15:48 UTC, homapf commented on .github/actions/promote-dev-dependencies/promote-dev-dependencies.sh
> +    local homa_dependencies_key="$2"
Done

2023-08-03 07:37 UTC, manelizzard approved these changes

2023-08-03 12:11 UTC, merged